config/routes.rb
Rails.application.routes.draw do
  resources :user_sessions

  resources :users

  root 'main#index'
  
  get 'login', to: 'user_sessions#new'
  get 'logout', to: 'user_sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
# app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # configuration here, see documentation for sub modules of Authlogic::Session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user

  before_filter :require_user

  private
  
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end
  
  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end

  def require_user
    unless current_user
      flash[:error] = "You must be logged in to access this page."
      redirect_to login_url
      return false
    end
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_filter :require_user

  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :set_user_session, only: [:destroy]
  before_filter :require_user, :only => :destroy
  
  # GET /user_sessions/new
  def new
    @user_session = UserSession.new
  end  

  # POST /user_sessions
  # POST /user_sessions.json
  def create
    @user_session = UserSession.new(user_session_params)

    respond_to do |format|
      if @user_session.save
        format.html { redirect_to root_url, notice: 'Successfully logged in.' }
        format.json { render :show, status: :created, location: @user_session }
      else
        format.html { render :new }
        format.json { render json: @user_session.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.json
  def destroy
    @user_session.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Successfully logged out.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_session
      @user_session = UserSession.find
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_session_params
      params[:user_session]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "R24e" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    
	<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>    
  </head>
  <body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= root_url %>">R24E</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
					<% if current_user %>
						<li>
	                        <%= link_to 'Edit Profile', edit_user_path(current_user.id) %>
	                    </li>
						<li>
	                        <%= link_to 'Manage Users', users_path %>
	                    </li>	                    
						<li>
							<%= link_to 'Logout', logout_path %>
						</li>
					<% else %>
						<li>
	                        <%= link_to 'Register', new_user_path %>
	                    </li>
	                    <li>
	                        <%= link_to 'Login', login_path %>
	                    </li>
					<% end %>                    
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    
    <%= bootstrap_flash %>
	<%= yield %>

	<!-- Footer -->
	<footer class="text-center">
	    <div class="footer-above">
	        <div class="container">
	            <div class="row">
	                <div class="footer-col col-md-4">
	                    <h3>Location</h3>
	                    <p>CRI</p>
	                </div>
	                <div class="footer-col col-md-4">
	                    <h3>Around the Web</h3>
	                    <ul class="list-inline">
	                        <li>
	                            <a href="https://www.facebook.com" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
	                        </li>
	                        <li>
	                            <a href="https://plus.google.com" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
	                        </li>
	                        <li>
	                            <a href="https://twitter.com" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
	                        </li>
	                        <li>
	                            <a href="https://www.linkedin.com" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
	                        </li>
	                    </ul>
	                </div>
	                <div class="footer-col col-md-4">
	                    <h3>About</h3>
	                    <p>I. Monge<br>RoR Dev.</p>
	                </div>
	            </div>
	        </div>
	    </div>
	    <div class="footer-below">
	        <div class="container">
	            <div class="row">
	                <div class="col-lg-12">
	                    Copyright &copy; R24E 2015
	                </div>
	            </div>
	        </div>
	    </div>
	</footer>
	
  </body>
</html>

app/views/main/index.html.erb
<!-- Header -->
<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
            	<%= image_tag("profile.png", class: 'img-responsive')  %>
                <div class="intro-text">
                    <span class="name">R24E</span>
                    <hr class="star-light">
                    <span class="skills">A Ruby on Rails learning website</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Portfolio Grid Section -->
<section id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Technologies</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 portfolio-item">
                <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
                    <div class="caption">
                        <div class="caption-content">
                            <i class="fa fa-search-plus fa-3x"></i>
                        </div>
                    </div>
                    <%= image_tag("image4.png", class: 'img-responsive')  %>
                </a>
            </div>
            <div class="col-sm-6 portfolio-item">
                <a href="#portfolioModal2" class="portfolio-link" data-toggle="modal">
                    <div class="caption">
                        <div class="caption-content">
                            <i class="fa fa-search-plus fa-3x"></i>
                        </div>
                    </div>
                    <%= image_tag("image2.png", class: 'img-responsive')  %>
                </a>
            </div>
            
            <div class="col-sm-6 portfolio-item">
                <a href="#portfolioModal4" class="portfolio-link" data-toggle="modal">
                    <div class="caption">
                        <div class="caption-content">
                            <i class="fa fa-search-plus fa-3x"></i>
                        </div>
                    </div>
                    <%= image_tag("image3.png", class: 'img-responsive')  %>
                </a>
            </div>
            <div class="col-sm-6 portfolio-item">
                <a href="#portfolioModal5" class="portfolio-link" data-toggle="modal">
                    <div class="caption">
                        <div class="caption-content">
                            <i class="fa fa-search-plus fa-3x"></i>
                        </div>
                    </div>
                    <%= image_tag("image1.png", class: 'img-responsive')  %>
                </a>
            </div>
            
        </div>
    </div>
</section>

<!-- About Section -->
<section class="success" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>About</h2>
                <hr class="star-light">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-lg-offset-2">
                <p>R24E is a self learning site for Ruby on Rails technologies.  This is a Rails 4+ and Ruby 2+ site, that uses bootrsrap for customization.  This site also uses authlogic gem for authentication, and is connected to a postgres db.</p>
            </div>
            <div class="col-lg-4">
                <p>This site uses Freelancer a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization.</p>
            </div>
            <div class="col-lg-8 col-lg-offset-2 text-center">
            </div>
        </div>
    </div>
</section>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-top page-scroll visible-xs visble-sm">
    <a class="btn btn-primary" href="#page-top">
        <i class="fa fa-chevron-up"></i>
    </a>
</div>

<!-- Portfolio Modals -->
<div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2>R24E</h2>
                        <hr class="star-primary">
                        <p>R24E A simple learning app</p>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2>R24E</h2>
                        <hr class="star-primary">
                        <p>R24E A simple learning app</p>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2>R24E</h2>
                        <hr class="star-primary">
                        <p>R24E A simple learning app</p>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal4" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2>R24E</h2>
                        <hr class="star-primary">
                        <p>R24E A simple learning app</p>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal5" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2>R24E</h2>
                        <hr class="star-primary">
                        <p>R24E A simple learning app</p>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal6" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2>R24E</h2>
                        <hr class="star-primary">
                        <p>R24E A simple learning app</p>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/user_sessions/_form.html.erb
<%= form_for(@user_session) do |f| %>
	<% if @user_session.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
		<div class="panel-heading">
        	<h3 class="panel-title"><%= pluralize(@user_session.errors.count, "error") %> prohibited from login into the application:</h3>
		</div>
      	<div class="panel-body">
        <ul>
      	<% @user_session.errors.full_messages.each do |message| %>
        	<li><%= message %></li>
      	<% end %>
      	</ul>
		</div>
	</div>
	<% end %>
	
    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
        	<%= f.label :username %><br>
    		<%= f.text_field :username, class:'form-control', placeholder:'Username'  %>
            <p class="help-block text-danger"></p>
        </div>
    </div>
    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
        	<%= f.label :password %><br>
    		<%= f.password_field :password, class:'form-control', placeholder:'Password'  %>
            <p class="help-block text-danger"></p>
        </div>
    </div>
    <br>
    <div id="success"></div>
    <div class="row">
        <div class="form-group col-xs-12">
        	<%= f.submit 'Login', class:'btn btn-success btn-lg' %>
        </div>
    </div>
<% end %>

app/views/user_sessions/new.html.erb
<!-- Contact Section -->
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Login</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
            	
                <%= render 'form' %>
                
            </div>
        </div>
    </div>
</section>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

    <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  	<% end %>
    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
        	<%= f.label :username %><br>
    		<%= f.text_field :username, :class => 'form-control', placeholder: 'Username' %>
    		<%= error_span(@user[:username]) %>
            <p class="help-block text-danger"></p>
        </div>
    </div>
    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
        	<%= f.label :email %><br>
    		<%= f.text_field :email, :class => 'form-control', placeholder: 'Email' %>
    		<%= error_span(@user[:email]) %>
            <p class="help-block text-danger"></p>
        </div>
    </div>    
    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
        	<%= f.label :password %><br>
    		<%= f.password_field :password, class:'form-control', placeholder:'Password'  %>
    		<%= error_span(@user[:password]) %>
            <p class="help-block text-danger"></p>
        </div>
    </div>
    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
        	<%= f.label :password_confirmation %><br>
    		<%= f.password_field :password_confirmation, class:'form-control', placeholder:'Password'  %>
    		<%= error_span(@user[:password_confirmation]) %>
            <p class="help-block text-danger"></p>
        </div>
    </div>    
    <br>
    <div id="success"></div>
    <div class="row">
        <div class="form-group col-xs-12">
        	<%= f.submit nil, :class => 'btn btn-success btn-l' %>
        	<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            users_path, :class => 'btn btn-default' %>
        </div>
    </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<!-- Contact Section -->
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
            	
                <%= render :partial => 'form' %>
                
            </div>
        </div>
    </div>
</section>

app/views/users/index.html.erb
<%- model_class = User -%>
<!-- Contact Section -->
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
            	
				<table class="table table-striped">
				  <thead>
				    <tr>
				      <th><%= model_class.human_attribute_name(:id) %></th>
				      <th><%= model_class.human_attribute_name(:username) %></th>
				      <th><%= model_class.human_attribute_name(:email) %></th>
				      <th><%= model_class.human_attribute_name(:created_at) %></th>
				      <th><%=t '.actions', :default => t("helpers.actions") %></th>
				    </tr>
				  </thead>
				  <tbody>
				    <% @users.each do |user| %>
				      <tr>
				        <td><%= link_to user.id, user_path(user) %></td>
				        <td><%= user.username %></td>
				        <td><%= user.email %></td>
				        <td><%= user.created_at.strftime('%B %e %Y') %></td>
				        <td>
				          <%= link_to t('.edit', :default => t("helpers.links.edit")),
				                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
				          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
				                      user_path(user),
				                      :method => :delete,
				                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
				                      :class => 'btn btn-xs btn-danger' %>
				        </td>
				      </tr>
				    <% end %>
				  </tbody>
				</table>
				
				<%= link_to t('.new', :default => t("helpers.links.new")),
				            new_user_path,
				            :class => 'btn btn-primary' %>
                
            </div>
        </div>
    </div>
</section>

app/views/users/new.html.erb
<%- model_class = User -%>
<!-- Contact Section -->
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
            	
                <%= render :partial => 'form' %>
                
            </div>
        </div>
    </div>
</section>

app/views/users/show.html.erb
<%- model_class = User -%>
<!-- Contact Section -->
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2><%=t '.title', :default => model_class.model_name.human.titleize %></h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            	
			<div class="col-lg-4 col-lg-offset-2">
                <p><strong><%= model_class.human_attribute_name(:username) %>:</strong></p>
                <p><strong><%= model_class.human_attribute_name(:email) %>:</strong></p>
            </div>
            <div class="col-lg-4">
                <p><%= @user.username %></p>
                <p><%= @user.email %></p>
            </div>
            
            <div class="col-lg-8 col-lg-offset-2 text-center">
            	<%= link_to t('.back', :default => t("helpers.links.back")),
				              users_path, :class => 'btn btn-default'  %>
				<%= link_to t('.edit', :default => t("helpers.links.edit")),
				              edit_user_path(@user), :class => 'btn btn-default' %>
				<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
				              user_path(@user),
				              :method => 'delete',
				              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
				              :class => 'btn btn-danger' %>
            
            </div>
        </div>
    </div>
</section>